// Static URL resolution for itinerary images.
// Uses pre-built manifests (generated by scripts/generate-itinerary-manifests.mjs)
// instead of import.meta.glob — no image binaries are bundled into the build.
//
// Variant resolution rules:
//   complete  → root assets only (never reads from variant subfolders)
//   essential → {folder}/essential/ override if it exists, else falls back to root
//   short     → {folder}/short/ override if it exists, else falls back to root
//
// Research variant resolution (same override → fallback pattern as gallery/day images):
//   complete  → root research/ only
//   essential → research/essential/ images if present
//             → research/essential/_hide marker if present → hide section (empty array)
//             → otherwise fallback to root research/
//   short     → same pattern for research/short/
//
// Maps are always variant-specific (map/complete/, map/essential/, map/short/).
// Itineraries without variant subfolders fall back to the legacy root map/ folder.
//
// Usage:
//   import { getGalleryImages, getResearchImages, getDayImage,
//            getCoverImage, getMapImage } from '../lib/itineraryImages';
//
//   // slug = itinerary.parentId ?? itinerary.id  (the content folder name)
//   // variant = itinerary.variant                ('premium'|'essential'|'short'|undefined)
//   const gallery  = getGalleryImages(slug, variant);
//   const research = getResearchImages(slug, variant);
//   const img      = getDayImage(slug, dayNumber, variant);
//   const cover    = getCoverImage(slug);
//   const map      = getMapImage(slug, variant);

import { MANIFESTS } from './itineraryManifests.js';

// ── Internal helpers ──────────────────────────────────────────────────────────

/**
 * Map 'premium' (legacy alias) and anything else unknown to 'complete'.
 * Returns one of: 'complete' | 'essential' | 'short'
 */
function normalizeVariant(variant) {
  if (variant === 'essential') return 'essential';
  if (variant === 'short')     return 'short';
  return 'complete'; // 'premium', 'complete', undefined, or unrecognised
}

/**
 * Convert a list of filenames + base URL to [{src, filename}] pairs.
 */
function toImageList(files, baseUrl) {
  return (files ?? []).map(filename => ({
    src: `${baseUrl}/${filename}`,
    filename,
  }));
}

/**
 * Shared variant-aware resolver for gallery and day-image buckets.
 * Returns { files: string[], sub: string|null }
 *   files — the resolved file list for this variant (may be empty)
 *   sub   — subfolder name ('essential' | 'short' | null for root)
 *
 * Three-state semantics for variant sub-arrays (null = absent, [] = empty, [...] = files):
 *   null  → variant folder does not exist → fall back to root
 *   []    → variant folder exists but is empty → explicit suppression: no image, no fallback
 *   [...] → variant folder has files → use them
 *
 * Handles both new object format { root, essential, short }
 * and legacy flat array format (treated as root, returns sub: null).
 *
 * Resolution order:
 *   complete  → root files only (no variant subfolder)
 *   essential → essential array:
 *               null → fall back to root
 *               []   → suppress (return empty, no fallback)
 *               [...] → use essential files
 *   short     → same pattern for short
 */
function resolveVariantBucket(bucket, variant) {
  const v = normalizeVariant(variant);

  // Legacy flat array — treat as root files with no variant subfolder
  if (Array.isArray(bucket)) return { files: bucket, sub: null };
  if (!bucket)               return { files: [],     sub: null };

  if (v === 'essential') {
    const ess = bucket.essential;              // null | [] | [file, ...]
    if (ess == null)    return { files: bucket.root ?? [], sub: null };   // absent → fallback
    if (ess.length > 0) return { files: ess,               sub: 'essential' }; // files → use
    return              { files: [],            sub: 'essential' };            // empty → suppress
  }

  if (v === 'short') {
    const sh = bucket.short;
    if (sh == null)    return { files: bucket.root ?? [], sub: null };
    if (sh.length > 0) return { files: sh,                sub: 'short' };
    return             { files: [],             sub: 'short' };
  }

  // complete: root only
  return { files: bucket.root ?? [], sub: null };
}

/**
 * Pick the preferred map filename from a list.
 * Prefers route-map.png, avoids -print variants, falls back to first file.
 * Returns a full URL string or null.
 */
function pickMapUrl(files, baseUrl) {
  if (!files || !files.length) return null;
  const preferred =
    files.find(f => f === 'route-map.png')           ||
    files.find(f => !f.includes('-print'))            ||
    files[0];
  return preferred ? `${baseUrl}/${preferred}` : null;
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Returns gallery images for the given asset slug and variant.
 *
 * complete  → root gallery only
 * essential → gallery/essential/ override if it exists, else root
 * short     → gallery/short/ override if it exists, else root
 *
 * @param {string}  slug    - Content folder name (itinerary.parentId ?? itinerary.id)
 * @param {string} [variant]
 * @returns {{ src: string, filename: string }[]}
 */
export function getGalleryImages(slug, variant) {
  const manifest = MANIFESTS[slug];
  if (!manifest) return [];
  const base = `/itineraries/${slug}/gallery`;
  const { files, sub } = resolveVariantBucket(manifest.gallery, variant);
  return toImageList(files, sub ? `${base}/${sub}` : base);
}

/**
 * Returns research images for the given asset slug and variant.
 *
 * complete  → root research/ only
 * essential → research/essential/ images if present
 *           → research/essential/_hide present → [] (hide section)
 *           → no variant folder → fallback to root research/
 * short     → same pattern for research/short/
 *
 * An empty array always signals that the research section should be hidden.
 *
 * @param {string}  slug
 * @param {string} [variant]
 * @returns {{ src: string, filename: string }[]}
 */
export function getResearchImages(slug, variant) {
  const manifest = MANIFESTS[slug];
  if (!manifest) return [];
  const v    = normalizeVariant(variant);
  const base = `/itineraries/${slug}/research`;

  if (v === 'essential') {
    const overrides = manifest.research.essential ?? [];
    if (overrides.length) return toImageList(overrides, `${base}/essential`);

    // Folder exists but intentionally empty → hide
    if (manifest.research.hideEssential) return [];

    // No variant folder at all → fallback to root
    return toImageList(manifest.research.root, base);
  }

  if (v === 'short') {
    const overrides = manifest.research.short ?? [];
    if (overrides.length) return toImageList(overrides, `${base}/short`);

    if (manifest.research.hideShort) return [];

    return toImageList(manifest.research.root, base);
  }

  // complete: root only
  return toImageList(manifest.research.root, base);
}

/**
 * Returns the URL for a single day image, or null if none exists.
 *
 * complete  → day-images/day{N}/{file}            (root only)
 * essential → day-images/day{N}/essential/{file}  → falls back to root
 * short     → day-images/day{N}/short/{file}      → falls back to root
 *
 * @param {string}  slug
 * @param {number}  dayNumber - 1-based day index
 * @param {string} [variant]
 * @returns {string|null}
 */
export function getDayImage(slug, dayNumber, variant) {
  const manifest = MANIFESTS[slug];
  if (!manifest) return null;
  const dayData = manifest.dayImages[dayNumber];
  if (!dayData) return null;
  const base = `/itineraries/${slug}/day-images/day${dayNumber}`;
  const { files, sub } = resolveVariantBucket(dayData, variant);
  if (!files.length) return null;
  return `${sub ? `${base}/${sub}` : base}/${files[0]}`;
}

/**
 * Returns up to 2 URLs for a day's images.
 * Applies the same variant resolution as getDayImage.
 *
 * @param {string}  slug
 * @param {number}  dayNumber
 * @param {string} [variant]
 * @returns {string[]}
 */
export function getDayImages(slug, dayNumber, variant) {
  const manifest = MANIFESTS[slug];
  if (!manifest) return [];
  const dayData = manifest.dayImages[dayNumber];
  if (!dayData) return [];
  const base = `/itineraries/${slug}/day-images/day${dayNumber}`;
  const { files, sub } = resolveVariantBucket(dayData, variant);
  const urlBase = sub ? `${base}/${sub}` : base;
  return files.slice(0, 2).map(f => `${urlBase}/${f}`);
}

/**
 * Returns the URL for the route map image, or null.
 *
 * Maps are variant-specific. Lookup order:
 *   complete  → map/complete/{file}, then legacy root map/ (backward compat)
 *   essential → map/essential/{file}, or null
 *   short     → map/short/{file}, or null
 *
 * @param {string}  slug
 * @param {string} [variant]
 * @returns {string|null}
 */
export function getMapImage(slug, variant) {
  const manifest = MANIFESTS[slug];
  if (!manifest) return null;
  const v    = normalizeVariant(variant);
  const base = `/itineraries/${slug}/map`;

  if (v === 'essential') {
    return pickMapUrl(manifest.map.essential, `${base}/essential`);
  }

  if (v === 'short') {
    return pickMapUrl(manifest.map.short, `${base}/short`);
  }

  // complete: try map/complete/ first, then legacy root map/
  const fromComplete = pickMapUrl(manifest.map.complete, `${base}/complete`);
  if (fromComplete) return fromComplete;

  return pickMapUrl(manifest.map.root, base);
}

/**
 * Returns the URL for the itinerary cover/hero image.
 * Uses heroFile from the manifest if available, else falls back to cover.jpg.
 *
 * @param {string} slug - Content folder name (use parentId for variants)
 * @returns {string}
 */
export function getCoverImage(slug) {
  const manifest = MANIFESTS[slug];
  const heroFile = manifest?.heroFile ?? 'cover.jpg';
  return `/itineraries/${slug}/${heroFile}`;
}
