// Static URL resolution for itinerary images.
// Uses pre-built manifests (generated by scripts/generate-itinerary-manifests.mjs)
// instead of import.meta.glob — no image binaries are bundled into the build.
//
// Three-state semantics apply uniformly to gallery, research, and day images:
//   null  (variant folder absent in content/)  → fall back to root
//   []    (variant folder exists but empty)    → suppress — return nothing, no fallback
//   [...] (variant folder has files)           → use those files
//
//   complete  → root assets only
//   essential → essential/ bucket (three-state above)
//   short     → short/ bucket (three-state above)
//
// Maps are always variant-specific (map/complete/, map/essential/, map/short/).
// Itineraries without variant subfolders fall back to the legacy root map/ folder.
//
// Usage:
//   import { getGalleryImages, getResearchImages, getDayImage,
//            getCoverImage, getMapImage } from '../lib/itineraryImages';
//
//   // slug = itinerary.parentId ?? itinerary.id  (the content folder name)
//   // variant = itinerary.variant                ('premium'|'essential'|'short'|undefined)
//   const gallery  = getGalleryImages(slug, variant);
//   const research = getResearchImages(slug, variant);
//   const img      = getDayImage(slug, dayNumber, variant);
//   const cover    = getCoverImage(slug);
//   const map      = getMapImage(slug, variant);

import { MANIFESTS } from './itineraryManifests.js';

// ── Internal helpers ──────────────────────────────────────────────────────────

/**
 * Map 'premium' (legacy alias) and anything else unknown to 'complete'.
 * Returns one of: 'complete' | 'essential' | 'short'
 */
function normalizeVariant(variant) {
  if (variant === 'essential') return 'essential';
  if (variant === 'short')     return 'short';
  return 'complete'; // 'premium', 'complete', undefined, or unrecognised
}

/**
 * Convert a list of filenames + base URL to [{src, filename}] pairs.
 */
function toImageList(files, baseUrl) {
  return (files ?? []).map(filename => ({
    src: `${baseUrl}/${filename}`,
    filename,
  }));
}

/**
 * Shared variant-aware resolver for gallery and day-image buckets.
 * Returns { files: string[], sub: string|null }
 *   files — the resolved file list for this variant (may be empty)
 *   sub   — subfolder name ('essential' | 'short' | null for root)
 *
 * Three-state semantics for variant sub-arrays (null = absent, [] = empty, [...] = files):
 *   null  → variant folder does not exist → fall back to root
 *   []    → variant folder exists but is empty → explicit suppression: no image, no fallback
 *   [...] → variant folder has files → use them
 *
 * Handles both new object format { root, essential, short }
 * and legacy flat array format (treated as root, returns sub: null).
 *
 * Resolution order:
 *   complete  → root files only (no variant subfolder)
 *   essential → essential array:
 *               null → fall back to root
 *               []   → suppress (return empty, no fallback)
 *               [...] → use essential files
 *   short     → same pattern for short
 */
function resolveVariantBucket(bucket, variant) {
  const v = normalizeVariant(variant);

  // Legacy flat array — treat as root files with no variant subfolder
  if (Array.isArray(bucket)) return { files: bucket, sub: null };
  if (!bucket)               return { files: [],     sub: null };

  if (v === 'essential') {
    const ess = bucket.essential;              // null | [] | [file, ...]
    if (ess == null)    return { files: bucket.root ?? [], sub: null };   // absent → fallback
    if (ess.length > 0) return { files: ess,               sub: 'essential' }; // files → use
    return              { files: [],            sub: 'essential' };            // empty → suppress
  }

  if (v === 'short') {
    const sh = bucket.short;
    if (sh == null)    return { files: bucket.root ?? [], sub: null };
    if (sh.length > 0) return { files: sh,                sub: 'short' };
    return             { files: [],             sub: 'short' };
  }

  // complete: root only
  return { files: bucket.root ?? [], sub: null };
}

/**
 * Pick the preferred map filename from a list.
 * Prefers route-map.png, avoids -print variants, falls back to first file.
 * Returns a full URL string or null.
 */
function pickMapUrl(files, baseUrl) {
  if (!files || !files.length) return null;
  const preferred =
    files.find(f => f === 'route-map.png')           ||
    files.find(f => !f.includes('-print'))            ||
    files[0];
  return preferred ? `${baseUrl}/${preferred}` : null;
}

// ── Public API ────────────────────────────────────────────────────────────────
// NOTE: this resolver reads from the pre-built MANIFESTS object (not the filesystem at runtime).
// MANIFESTS was generated by scripts/generate-itinerary-manifests.mjs from content/itineraries/.
// To see what slug manifests exist: Object.keys(MANIFESTS)

export function debugManifestRoot(slug) {
  const manifest = MANIFESTS[slug];
  console.log('FILESYSTEM ROOT', {
    rootPathInUse: 'MANIFESTS (pre-built from content/itineraries)',
    manifestExists: !!manifest,
    manifestKeys: manifest ? Object.keys(manifest) : [],
    allManifestSlugs: Object.keys(MANIFESTS),
  });
  return manifest;
}

/**
 * Returns gallery images for the given asset slug and variant.
 *
 * complete  → root gallery only
 * essential → gallery/essential/ override if it exists, else root
 * short     → gallery/short/ override if it exists, else root
 *
 * @param {string}  slug    - Content folder name (itinerary.parentId ?? itinerary.id)
 * @param {string} [variant]
 * @returns {{ src: string, filename: string }[]}
 */
export function getGalleryImages(slug, variant) {
  const manifest = MANIFESTS[slug];
  if (!manifest) return [];
  const base = `/itineraries/${slug}/gallery`;
  const { files, sub } = resolveVariantBucket(manifest.gallery, variant);
  console.log('GALLERY CHECK', {
    baseSlug: slug,
    variant: variant || null,
    manifestGallery: manifest.gallery,
    chosenMode: sub ? `variant/${sub}` : 'root',
    chosenFiles: files,
  });
  return toImageList(files, sub ? `${base}/${sub}` : base);
}

/**
 * Returns research images for the given asset slug and variant.
 * Uses the same three-state semantics as gallery and day images via resolveVariantBucket:
 *   null  → variant folder absent → fall back to root research/
 *   []    → variant folder exists but empty → suppress (return [])
 *   [...] → use those files
 *
 * @param {string}  slug
 * @param {string} [variant]
 * @returns {{ src: string, filename: string }[]}
 */
export function getResearchImages(slug, variant) {
  const manifest = MANIFESTS[slug];
  if (!manifest) return [];
  const base = `/itineraries/${slug}/research`;
  const { files, sub } = resolveVariantBucket(manifest.research, variant);
  console.log('RESEARCH CHECK', {
    baseSlug: slug,
    variant: variant || null,
    manifestResearch: manifest.research,
    chosenMode: sub ? `variant/${sub}` : 'root',
    chosenFiles: files,
  });
  return toImageList(files, sub ? `${base}/${sub}` : base);
}

/**
 * Returns the URL for a single day image, or null if none exists.
 *
 * complete  → day-images/day{N}/{file}            (root only)
 * essential → day-images/day{N}/essential/{file}  → falls back to root
 * short     → day-images/day{N}/short/{file}      → falls back to root
 *
 * @param {string}  slug
 * @param {number}  dayNumber - 1-based day index
 * @param {string} [variant]
 * @returns {string|null}
 */
export function getDayImage(slug, dayNumber, variant) {
  const manifest = MANIFESTS[slug];
  if (!manifest) return null;
  const dayData = manifest.dayImages[dayNumber];
  if (!dayData) return null;
  const base = `/itineraries/${slug}/day-images/day${dayNumber}`;
  const { files, sub } = resolveVariantBucket(dayData, variant);
  if (!files.length) return null;
  return `${sub ? `${base}/${sub}` : base}/${files[0]}`;
}

/**
 * Returns up to 2 URLs for a day's images.
 * Applies the same variant resolution as getDayImage.
 *
 * @param {string}  slug
 * @param {number}  dayNumber
 * @param {string} [variant]
 * @returns {string[]}
 */
export function getDayImages(slug, dayNumber, variant) {
  const manifest = MANIFESTS[slug];
  if (!manifest) return [];
  const dayData = manifest.dayImages[dayNumber];
  const base    = `/itineraries/${slug}/day-images/day${dayNumber}`;
  if (!dayData) {
    console.log('DAY IMAGE CHECK', { day: dayNumber, baseSlug: slug, variant: variant || null, manifestDayData: null, chosenSource: 'absent', chosenFiles: [] });
    return [];
  }
  const { files, sub } = resolveVariantBucket(dayData, variant);
  const urlBase = sub ? `${base}/${sub}` : base;
  console.log('DAY IMAGE CHECK', {
    day: dayNumber,
    baseSlug: slug,
    variant: variant || null,
    defaultPath: base,
    variantPath: `${base}/${variant || '?'}`,
    manifestDayData: dayData,
    resolvedFiles: files,
    sub: sub || null,
    chosenSource: sub ? `variant/${sub}` : 'root',
    chosenPath: urlBase,
  });
  return files.slice(0, 2).map(f => `${urlBase}/${f}`);
}

/**
 * Returns the URL for the route map image, or null.
 *
 * Maps are variant-specific. Lookup order:
 *   complete  → map/complete/{file}, then legacy root map/ (backward compat)
 *   essential → map/essential/{file}, or null
 *   short     → map/short/{file}, or null
 *
 * @param {string}  slug
 * @param {string} [variant]
 * @returns {string|null}
 */
export function getMapImage(slug, variant) {
  const manifest = MANIFESTS[slug];
  if (!manifest) return null;
  const v    = normalizeVariant(variant);
  const base = `/itineraries/${slug}/map`;

  if (v === 'essential') {
    return pickMapUrl(manifest.map.essential, `${base}/essential`);
  }

  if (v === 'short') {
    return pickMapUrl(manifest.map.short, `${base}/short`);
  }

  // complete: try map/complete/ first, then legacy root map/
  const fromComplete = pickMapUrl(manifest.map.complete, `${base}/complete`);
  if (fromComplete) return fromComplete;

  return pickMapUrl(manifest.map.root, base);
}

/**
 * Returns the URL for the itinerary cover/hero image.
 * Uses heroFile from the manifest if available, else falls back to cover.jpg.
 *
 * @param {string} slug - Content folder name (use parentId for variants)
 * @returns {string}
 */
export function getCoverImage(slug) {
  const manifest = MANIFESTS[slug];
  const heroFile = manifest?.heroFile ?? 'cover.jpg';
  return `/itineraries/${slug}/${heroFile}`;
}
