// AUTO-GENERATED by scripts/generate-itinerary-manifests.mjs
// Do not edit manually. Run `node scripts/generate-itinerary-manifests.mjs` to regenerate.
// eslint-disable-next-line

/** @type {Record<string, import("./itineraryImages").ItineraryManifest>} */
export const MANIFESTS = {
  "albania-riviera-mountains": {
    "slug": "albania-riviera-mountains",
    "title": "Albania",
    "heroFile": null,
    "gallery": {
      "root": [],
      "essential": [],
      "short": []
    },
    "research": {
      "root": [],
      "essential": [],
      "short": [],
      "hideEssential": false,
      "hideShort": false
    },
    "dayImages": {
      "1": {
        "root": [],
        "essential": [],
        "short": []
      },
      "2": {
        "root": [],
        "essential": [],
        "short": []
      },
      "3": {
        "root": [],
        "essential": [],
        "short": []
      },
      "4": {
        "root": [],
        "essential": [],
        "short": []
      },
      "5": {
        "root": [],
        "essential": [],
        "short": []
      },
      "6": {
        "root": [],
        "essential": [],
        "short": []
      },
      "7": {
        "root": [],
        "essential": [],
        "short": []
      },
      "8": {
        "root": [],
        "essential": [],
        "short": []
      },
      "9": {
        "root": [],
        "essential": [],
        "short": []
      },
      "10": {
        "root": [],
        "essential": [],
        "short": []
      }
    },
    "map": {
      "root": [],
      "complete": [],
      "essential": [],
      "short": []
    }
  },
  "bali-island-journey": {
    "slug": "bali-island-journey",
    "title": "Bali",
    "heroFile": null,
    "gallery": {
      "root": [
        "arrozais.jpg",
        "casa-sideman.jpg",
        "cascata.jpg",
        "floating-breakfast.jpg",
        "piscina-infinita.jpg",
        "praia-rocha.png",
        "swing-red-dress.jpg"
      ],
      "essential": [],
      "short": []
    },
    "research": {
      "root": [
        "foto-dancers.jpg",
        "selfie-arrozais.jpg",
        "selfie-piscina-infinita.jpg"
      ],
      "essential": [],
      "short": [],
      "hideEssential": false,
      "hideShort": false
    },
    "dayImages": {
      "1": {
        "root": [
          "day1.jpeg"
        ],
        "essential": [],
        "short": []
      },
      "2": {
        "root": [
          "day1.jpeg"
        ],
        "essential": [],
        "short": []
      },
      "3": {
        "root": [
          "day3.jpeg"
        ],
        "essential": [],
        "short": []
      },
      "4": {
        "root": [
          "day4.jpeg"
        ],
        "essential": [],
        "short": []
      },
      "5": {
        "root": [
          "day5.jpg"
        ],
        "essential": [],
        "short": []
      },
      "6": {
        "root": [
          "day6.jpg"
        ],
        "essential": [],
        "short": []
      },
      "7": {
        "root": [
          "day7.jpeg"
        ],
        "essential": [],
        "short": []
      },
      "8": {
        "root": [
          "day6.jpeg"
        ],
        "essential": [],
        "short": []
      },
      "9": {
        "root": [
          "day9.jpeg"
        ],
        "essential": [],
        "short": []
      },
      "10": {
        "root": [
          "day10.jpeg"
        ],
        "essential": [],
        "short": []
      }
    },
    "map": {
      "root": [],
      "complete": [],
      "essential": [],
      "short": []
    }
  },
  "brazil-coastal-journey": {
    "slug": "brazil-coastal-journey",
    "title": "Brazil",
    "heroFile": null,
    "gallery": {
      "root": [
        "angra-2.jpg",
        "angra.jpg",
        "buzios-night.jpg",
        "cabo-frio.jpg",
        "cascata.png",
        "catamara.jpg",
        "foto-morro.jpg"
      ],
      "essential": [],
      "short": []
    },
    "research": {
      "root": [
        "barco-2.jpg",
        "cris-barco.jpg",
        "cris-praia.jpg"
      ],
      "essential": [],
      "short": [],
      "hideEssential": false,
      "hideShort": false
    },
    "dayImages": {
      "1": {
        "root": [],
        "essential": [],
        "short": []
      },
      "2": {
        "root": [],
        "essential": [],
        "short": []
      },
      "3": {
        "root": [],
        "essential": [],
        "short": []
      },
      "4": {
        "root": [],
        "essential": [],
        "short": []
      },
      "5": {
        "root": [],
        "essential": [],
        "short": []
      },
      "6": {
        "root": [],
        "essential": [],
        "short": []
      },
      "7": {
        "root": [],
        "essential": [],
        "short": []
      },
      "8": {
        "root": [],
        "essential": [],
        "short": []
      },
      "9": {
        "root": [],
        "essential": [],
        "short": []
      },
      "10": {
        "root": [],
        "essential": [],
        "short": []
      },
      "11": {
        "root": [],
        "essential": [],
        "short": []
      },
      "12": {
        "root": [],
        "essential": [],
        "short": []
      }
    },
    "map": {
      "root": [],
      "complete": [],
      "essential": [],
      "short": []
    }
  },
  "budapest-city-break": {
    "slug": "budapest-city-break",
    "title": "Budapest",
    "heroFile": null,
    "gallery": {
      "root": [
        "castle.jpeg",
        "castle2.jpeg",
        "danube.jpeg",
        "street.jpeg"
      ],
      "essential": [],
      "short": []
    },
    "research": {
      "root": [
        "couple-castle.jpeg",
        "selfie-boat.jpeg",
        "selfie-danube.jpeg"
      ],
      "essential": [],
      "short": [],
      "hideEssential": false,
      "hideShort": false
    },
    "dayImages": {
      "1": {
        "root": [],
        "essential": [],
        "short": []
      },
      "2": {
        "root": [],
        "essential": [],
        "short": []
      },
      "3": {
        "root": [],
        "essential": [],
        "short": []
      }
    },
    "map": {
      "root": [],
      "complete": [],
      "essential": [],
      "short": []
    }
  },
  "california-american-west": {
    "slug": "california-american-west",
    "title": null,
    "heroFile": null,
    "gallery": {
      "root": [
        "1715789658-yosemite-fall.jpg",
        "Antelope-Canyon.jpg",
        "Arizona_Route_66_Road.jpg",
        "Malibu.jpg",
        "Pacific-Coast-Highway.jpeg",
        "cable-cars-downtown-san-francisco.jpg.jpeg",
        "chateau-montelena.jpg",
        "grand-canyon-ear.jpg",
        "hollywood.jpg",
        "national-park-express-grand-canyon.jpeg"
      ],
      "essential": [
        "1715789658-yosemite-fall.jpg",
        "Arizona_Route_66_Road.jpg",
        "Malibu.jpg",
        "cable-cars-downtown-san-francisco.jpg.jpeg",
        "grand-canyon-ear.jpg",
        "hollywood.jpg",
        "national-park-express-grand-canyon.jpeg"
      ],
      "short": [
        "1-Pacific-Coast-Highway.jpeg",
        "Malibu.jpg",
        "cable-cars-downtown-san-francisco.jpg.jpeg",
        "hollywood.jpg"
      ]
    },
    "research": {
      "root": [
        "66.jpg",
        "cavalo.jpg",
        "grand-canyon.jpg"
      ],
      "essential": [],
      "short": [],
      "hideEssential": false,
      "hideShort": false
    },
    "dayImages": {
      "1": {
        "root": [
          "day1.jpeg"
        ],
        "essential": [],
        "short": []
      },
      "2": {
        "root": [
          "day2.jpeg"
        ],
        "essential": [],
        "short": []
      },
      "3": {
        "root": [
          "day3.jpeg"
        ],
        "essential": [
          "day3-essential.jpg"
        ],
        "short": [
          "short-day3.jpeg"
        ]
      },
      "4": {
        "root": [
          "day4.jpeg"
        ],
        "essential": [],
        "short": [
          "short-day4.jpg"
        ]
      },
      "5": {
        "root": [
          "day5.jpeg"
        ],
        "essential": [],
        "short": [
          "short-day5.jpeg"
        ]
      },
      "6": {
        "root": [
          "day6.jpg"
        ],
        "essential": [],
        "short": [
          "short-day6.jpg"
        ]
      },
      "7": {
        "root": [
          "day7.jpg"
        ],
        "essential": [],
        "short": [
          "day13.jpg"
        ]
      },
      "8": {
        "root": [
          "day8.jpg"
        ],
        "essential": [],
        "short": [
          "day16.jpg"
        ]
      },
      "9": {
        "root": [
          "day9.jpeg"
        ],
        "essential": [],
        "short": []
      },
      "10": {
        "root": [
          "day10.jpeg"
        ],
        "essential": [
          "day10-essential.jpg"
        ],
        "short": []
      },
      "11": {
        "root": [
          "day11.jpg"
        ],
        "essential": [
          "day13.jpg"
        ],
        "short": []
      },
      "12": {
        "root": [
          "day12.jpg"
        ],
        "essential": [
          "day16.jpg"
        ],
        "short": []
      },
      "13": {
        "root": [
          "day13.jpg"
        ],
        "essential": [],
        "short": []
      },
      "14": {
        "root": [
          "day14.jpg"
        ],
        "essential": [],
        "short": []
      },
      "15": {
        "root": [
          "day15.jpg"
        ],
        "essential": [],
        "short": []
      },
      "16": {
        "root": [
          "day16.jpg"
        ],
        "essential": [],
        "short": []
      }
    },
    "map": {
      "root": [
        "route-map.png"
      ],
      "complete": [],
      "essential": [],
      "short": []
    }
  },
  "japan-grand-cultural-journey": {
    "slug": "japan-grand-cultural-journey",
    "title": "Japan",
    "heroFile": "cover.jpg",
    "gallery": {
      "root": [
        "1.kanazawa.jpg",
        "Shibuya-Crossing.jpg",
        "arashiyama.jpg",
        "dotonburi.jpg",
        "food.jpg",
        "food2.jpg",
        "garden-nation-kyoto.jpg",
        "hakone.jpg",
        "kinkaku.jpg",
        "kurashiki.jpg",
        "myagawa.jpg",
        "niio-castle.jpg",
        "okayama.jpg",
        "shirakawa-go.jpeg",
        "shitenno.jpg",
        "wagyu.jpeg"
      ],
      "essential": [],
      "short": []
    },
    "research": {
      "root": [
        "cris-florest.jpg",
        "cris-shirakawa-go.jpg",
        "cris-temple.jpg",
        "kyoto-vanda.jpg",
        "selfie.jpg",
        "vanda-veado.jpg"
      ],
      "essential": [],
      "short": [],
      "hideEssential": false,
      "hideShort": false
    },
    "dayImages": {
      "1": {
        "root": [
          "Shinjuku.jpg"
        ],
        "essential": [],
        "short": []
      },
      "2": {
        "root": [
          "day2.jpg"
        ],
        "essential": [],
        "short": []
      },
      "3": {
        "root": [
          "Shibuya-Crossing.jpg"
        ],
        "essential": [],
        "short": []
      },
      "4": {
        "root": [
          "Kanazawa.jpg"
        ],
        "essential": [],
        "short": []
      },
      "5": {
        "root": [
          "Wajima-Morning-Market.jpeg"
        ],
        "essential": [],
        "short": []
      },
      "6": {
        "root": [
          "Shirakawa-go.jpeg"
        ],
        "essential": [],
        "short": []
      },
      "7": {
        "root": [
          "Takayama.jpg"
        ],
        "essential": [],
        "short": []
      },
      "8": {
        "root": [
          "Hida-Folk-Village.jpg"
        ],
        "essential": [],
        "short": []
      },
      "9": {
        "root": [
          "Fushimi-Inari.jpg"
        ],
        "essential": [],
        "short": []
      },
      "10": {
        "root": [
          "Tenryu-ji.jpg"
        ],
        "essential": [],
        "short": []
      },
      "11": {
        "root": [
          "Nara.jpg"
        ],
        "essential": [],
        "short": []
      },
      "12": {
        "root": [
          "Kyoto.jpeg"
        ],
        "essential": [],
        "short": []
      },
      "13": {
        "root": [
          "Osaka.jpeg"
        ],
        "essential": [],
        "short": []
      },
      "14": {
        "root": [
          "Koyasan.jpg"
        ],
        "essential": [],
        "short": []
      },
      "15": {
        "root": [
          "Himeji.jpg"
        ],
        "essential": [],
        "short": []
      },
      "16": {
        "root": [
          "Okayama.jpg"
        ],
        "essential": [],
        "short": []
      },
      "17": {
        "root": [
          "hakone.jpg"
        ],
        "essential": [],
        "short": []
      },
      "18": {
        "root": [
          "tokyo.jpg"
        ],
        "essential": [],
        "short": []
      }
    },
    "map": {
      "root": [
        "route-map-print.png",
        "route-map.png"
      ],
      "complete": [],
      "essential": [],
      "short": []
    }
  },
  "morocco-motorcycle-expedition": {
    "slug": "morocco-motorcycle-expedition",
    "title": "Morocco Motorcycle Expedition",
    "heroFile": "cover.jpg",
    "gallery": {
      "root": [
        "20240213_075323.jpg",
        "20240214_101727.jpg",
        "IMG_1467.jpg",
        "IMG_1577.jpg",
        "IMG_1692.jpg",
        "IMG_1709.jpg",
        "IMG_20240214_104318.jpg",
        "chefchaouen.png",
        "marraquexe-capa.jpg",
        "moto-2.png",
        "moto.png",
        "sahar.png",
        "sun-rise.png"
      ],
      "essential": [],
      "short": []
    },
    "research": {
      "root": [
        "20240212_131501.jpg",
        "20240212_141911.jpg",
        "beach.jpeg"
      ],
      "essential": [],
      "short": [],
      "hideEssential": false,
      "hideShort": false
    },
    "dayImages": {
      "1": {
        "root": [
          "chefchaouen.jpeg"
        ],
        "essential": [],
        "short": []
      },
      "2": {
        "root": [
          "Errachidia.jpg"
        ],
        "essential": [],
        "short": []
      },
      "3": {
        "root": [
          "Aït Benhaddou.jpg"
        ],
        "essential": [],
        "short": []
      },
      "4": {
        "root": [
          "Ouarzazate.jpg"
        ],
        "essential": [],
        "short": []
      },
      "5": {
        "root": [
          "Merzouga-quad-dunes.jpg"
        ],
        "essential": [],
        "short": []
      },
      "6": {
        "root": [
          "marrakech.jpeg"
        ],
        "essential": [],
        "short": []
      },
      "7": {
        "root": [
          "Oualidia.jpg"
        ],
        "essential": [],
        "short": []
      },
      "8": {
        "root": [
          "Hassan-II-Mosque.jpg"
        ],
        "essential": [],
        "short": []
      }
    },
    "map": {
      "root": [],
      "complete": [],
      "essential": [],
      "short": []
    }
  },
  "normandy-brittany-loire": {
    "slug": "normandy-brittany-loire",
    "title": "Normandy, Brittany & Loire",
    "heroFile": null,
    "gallery": {
      "root": [
        "1_chateau-gallard3.jpg",
        "chambord.jpg",
        "charbord.jpg",
        "etretat.png",
        "market.png",
        "mont-saint-michel-2.png",
        "porto-honfleur.png"
      ],
      "essential": [],
      "short": []
    },
    "research": {
      "root": [
        "bekas.jpeg",
        "chambord-bekas2.jpeg",
        "saint-malo-cris.jpeg"
      ],
      "essential": [],
      "short": [],
      "hideEssential": false,
      "hideShort": false
    },
    "dayImages": {
      "1": {
        "root": [],
        "essential": [],
        "short": []
      },
      "2": {
        "root": [],
        "essential": [],
        "short": []
      },
      "3": {
        "root": [],
        "essential": [],
        "short": []
      },
      "4": {
        "root": [],
        "essential": [],
        "short": []
      }
    },
    "map": {
      "root": [],
      "complete": [],
      "essential": [],
      "short": []
    }
  },
  "northern-england-roadtrip": {
    "slug": "northern-england-roadtrip",
    "title": "Northern England",
    "heroFile": null,
    "gallery": {
      "root": [
        "1_old_castle.jpg",
        "castle_harrypotter.jpg",
        "castle_town.jpg",
        "church.jpg",
        "foto-morro.jpg",
        "hp_atrio.jpg",
        "landscape.jpg",
        "palace.jpg",
        "river.jpg",
        "rocks.jpg"
      ],
      "essential": [],
      "short": []
    },
    "research": {
      "root": [
        "cris_river.jpg",
        "selfie_old_castle.jpg",
        "selfie_york.jpg"
      ],
      "essential": [],
      "short": [],
      "hideEssential": false,
      "hideShort": false
    },
    "dayImages": {
      "1": {
        "root": [
          "day1.jpg"
        ],
        "essential": [],
        "short": []
      },
      "2": {
        "root": [
          "day2.jpg"
        ],
        "essential": [],
        "short": []
      },
      "3": {
        "root": [
          "day3.jpg"
        ],
        "essential": [],
        "short": []
      },
      "4": {
        "root": [
          "day4.jpg"
        ],
        "essential": [],
        "short": []
      }
    },
    "map": {
      "root": [],
      "complete": [],
      "essential": [],
      "short": []
    }
  },
  "philippines-island-journey": {
    "slug": "philippines-island-journey",
    "title": "Philippines",
    "heroFile": null,
    "gallery": {
      "root": [],
      "essential": [],
      "short": []
    },
    "research": {
      "root": [],
      "essential": [],
      "short": [],
      "hideEssential": false,
      "hideShort": false
    },
    "dayImages": {
      "1": {
        "root": [
          "day1.jpg"
        ],
        "essential": [],
        "short": []
      },
      "2": {
        "root": [
          "day2.jpg"
        ],
        "essential": [],
        "short": []
      },
      "3": {
        "root": [
          "day3.jpg"
        ],
        "essential": [],
        "short": []
      },
      "4": {
        "root": [
          "day4.jpg"
        ],
        "essential": [],
        "short": []
      },
      "5": {
        "root": [
          "day5.jpg"
        ],
        "essential": [],
        "short": []
      },
      "6": {
        "root": [
          "day7.jpg"
        ],
        "essential": [],
        "short": []
      },
      "7": {
        "root": [
          "day6.jpeg"
        ],
        "essential": [],
        "short": []
      },
      "8": {
        "root": [
          "day8.jpg"
        ],
        "essential": [],
        "short": []
      },
      "9": {
        "root": [
          "day9.jpg"
        ],
        "essential": [],
        "short": []
      },
      "10": {
        "root": [
          "day10.jpeg"
        ],
        "essential": [],
        "short": []
      },
      "11": {
        "root": [
          "day11.jpg"
        ],
        "essential": [],
        "short": []
      },
      "12": {
        "root": [
          "day12.jpg"
        ],
        "essential": [],
        "short": []
      },
      "13": {
        "root": [
          "day13.jpg"
        ],
        "essential": [],
        "short": []
      },
      "14": {
        "root": [
          "day14.jpg"
        ],
        "essential": [],
        "short": []
      },
      "15": {
        "root": [
          "day15.jpg"
        ],
        "essential": [],
        "short": []
      },
      "16": {
        "root": [
          "day16.jpg"
        ],
        "essential": [],
        "short": []
      },
      "17": {
        "root": [
          "day17.jpeg"
        ],
        "essential": [],
        "short": []
      }
    },
    "map": {
      "root": [],
      "complete": [],
      "essential": [],
      "short": []
    }
  },
  "puglia-road-journey": {
    "slug": "puglia-road-journey",
    "title": "Puglia",
    "heroFile": null,
    "gallery": {
      "root": [
        "1_matera.jpeg",
        "alberobelo-center.png",
        "lecce3.jpg",
        "praca-duomo-lecce.png"
      ],
      "essential": [],
      "short": []
    },
    "research": {
      "root": [
        "matera_cris.jpg",
        "selfie_alberobelo.jpg",
        "selfie_alberobelo_2.jpg"
      ],
      "essential": [],
      "short": [],
      "hideEssential": false,
      "hideShort": false
    },
    "dayImages": {
      "1": {
        "root": [],
        "essential": [],
        "short": []
      },
      "2": {
        "root": [],
        "essential": [],
        "short": []
      },
      "3": {
        "root": [],
        "essential": [],
        "short": []
      },
      "4": {
        "root": [],
        "essential": [],
        "short": []
      }
    },
    "map": {
      "root": [],
      "complete": [],
      "essential": [],
      "short": []
    }
  },
  "rome-4-day-city-break": {
    "slug": "rome-4-day-city-break",
    "title": "Rome",
    "heroFile": null,
    "gallery": {
      "root": [
        "Italy_Rome_Saint_Peter.jpg",
        "Trevi-Fountain.jpeg",
        "pantheom.jpg",
        "rome-colosseum-.jpg"
      ],
      "essential": [],
      "short": []
    },
    "research": {
      "root": [
        "IMG_1189.jpg",
        "IMG_1476.jpg",
        "IMG_2289.jpg"
      ],
      "essential": [],
      "short": [],
      "hideEssential": false,
      "hideShort": false
    },
    "dayImages": {
      "1": {
        "root": [],
        "essential": [],
        "short": []
      },
      "2": {
        "root": [],
        "essential": [],
        "short": []
      },
      "3": {
        "root": [],
        "essential": [],
        "short": []
      },
      "4": {
        "root": [
          "baths-of-caracalla.jpeg"
        ],
        "essential": [],
        "short": []
      }
    },
    "map": {
      "root": [],
      "complete": [],
      "essential": [],
      "short": []
    }
  },
  "vienna-imperial-journey": {
    "slug": "vienna-imperial-journey",
    "title": "Vienna",
    "heroFile": null,
    "gallery": {
      "root": [
        "1-Graben_Viena.jpg",
        "2-escola.png",
        "3-ride-school.jpg",
        "Que-ver-en-Viena.jpg"
      ],
      "essential": [],
      "short": []
    },
    "research": {
      "root": [
        "cris-comer.png",
        "cris-vanda-street.jpg",
        "cris-vanda.png"
      ],
      "essential": [],
      "short": [],
      "hideEssential": false,
      "hideShort": false
    },
    "dayImages": {
      "1": {
        "root": [],
        "essential": [],
        "short": []
      },
      "2": {
        "root": [],
        "essential": [],
        "short": []
      },
      "3": {
        "root": [],
        "essential": [],
        "short": []
      },
      "4": {
        "root": [],
        "essential": [],
        "short": []
      }
    },
    "map": {
      "root": [],
      "complete": [],
      "essential": [],
      "short": []
    }
  }
};
