import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const S = StyleSheet.create({
  page: {
    paddingTop: 56, paddingBottom: 72, paddingHorizontal: 56,
    fontFamily: 'Helvetica', backgroundColor: '#FFFFFF',
    color: '#1C1A16',
  },
  label: {
    fontSize: 7.5, fontFamily: 'Helvetica-Bold',
    letterSpacing: 2.5, textTransform: 'uppercase',
    color: '#1B6B65', marginBottom: 8,
  },
  h1: {
    fontSize: 26, fontFamily: 'Helvetica-Bold',
    color: '#1C1A16', marginBottom: 10, lineHeight: 1.2,
  },
  overview: {
    fontSize: 11, color: '#4A433A', lineHeight: 1.7, marginBottom: 8,
  },
  duration: {
    fontSize: 9, fontFamily: 'Helvetica-Bold',
    color: '#1B6B65', marginBottom: 24,
  },
  divider: {
    borderBottomWidth: 0.75, borderBottomColor: '#E8E3DA', marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 14, fontFamily: 'Helvetica-Bold',
    color: '#1C1A16', marginBottom: 12, marginTop: 24,
  },
  bullet: {
    fontSize: 10, color: '#4A433A', marginBottom: 5, lineHeight: 1.5,
    paddingLeft: 10,
  },
  dayWrap: { marginBottom: 12 },
  dayLabel: {
    fontSize: 7.5, fontFamily: 'Helvetica-Bold', letterSpacing: 1.5,
    textTransform: 'uppercase', color: '#1B6B65', marginBottom: 3,
  },
  dayTitle: {
    fontSize: 12, fontFamily: 'Helvetica-Bold',
    color: '#1C1A16', marginBottom: 4,
  },
  dayDesc: { fontSize: 10, color: '#6B6156', lineHeight: 1.65 },
  hotelWrap: { marginBottom: 12 },
  hotelName: {
    fontSize: 11, fontFamily: 'Helvetica-Bold',
    color: '#1C1A16', marginBottom: 2,
  },
  hotelType: {
    fontSize: 7.5, fontFamily: 'Helvetica-Bold', letterSpacing: 1,
    textTransform: 'uppercase', color: '#C9A96E', marginBottom: 3,
  },
  hotelNote: { fontSize: 10, color: '#6B6156', lineHeight: 1.5 },
  footer: {
    position: 'absolute', bottom: 28, left: 56, right: 56,
    fontSize: 8, color: '#B5AA99', textAlign: 'center',
    borderTopWidth: 0.75, borderTopColor: '#E8E3DA', paddingTop: 8,
  },
});

// Accepts both AI result shape ({ days[].day }) and DB shape ({ days[].dayNumber })
export function TripPDF({ trip }) {
  const highlights  = Array.isArray(trip.highlights)  ? trip.highlights  : [];
  const hotels      = Array.isArray(trip.hotels)      ? trip.hotels      : [];
  const experiences = Array.isArray(trip.experiences) ? trip.experiences : [];
  const days        = Array.isArray(trip.days)        ? trip.days        : [];

  return (
    <Document title={`${trip.destination} Itinerary`} author="HiddenAtlas">
      <Page size="A4" style={S.page}>

        {/* Header */}
        {trip.country ? <Text style={S.label}>{trip.country}</Text> : null}
        <Text style={S.h1}>{trip.destination}</Text>
        {trip.overview ? <Text style={S.overview}>{trip.overview}</Text> : null}
        {trip.duration ? <Text style={S.duration}>{trip.duration}</Text> : null}
        <View style={S.divider} />

        {/* Highlights */}
        {highlights.length > 0 && (
          <View>
            <Text style={S.sectionTitle}>Trip Highlights</Text>
            {highlights.map((h, i) => (
              <Text key={i} style={S.bullet}>• {h}</Text>
            ))}
          </View>
        )}

        {/* Days */}
        {days.length > 0 && (
          <View>
            <Text style={S.sectionTitle}>Day by Day</Text>
            {days.map((day, i) => (
              <View key={day.id || i} style={S.dayWrap}>
                <Text style={S.dayLabel}>Day {day.dayNumber ?? day.day}</Text>
                <Text style={S.dayTitle}>{day.title}</Text>
                <Text style={S.dayDesc}>{day.description}</Text>
              </View>
            ))}
          </View>
        )}

        {/* Hotels */}
        {hotels.length > 0 && (
          <View>
            <Text style={S.sectionTitle}>Where to Stay</Text>
            {hotels.map((h, i) => (
              <View key={i} style={S.hotelWrap}>
                <Text style={S.hotelName}>{h.name}</Text>
                {h.type ? <Text style={S.hotelType}>{h.type}</Text> : null}
                {h.note ? <Text style={S.hotelNote}>{h.note}</Text> : null}
              </View>
            ))}
          </View>
        )}

        {/* Experiences */}
        {experiences.length > 0 && (
          <View>
            <Text style={S.sectionTitle}>Key Experiences</Text>
            {experiences.map((exp, i) => (
              <Text key={i} style={S.bullet}>• {exp}</Text>
            ))}
          </View>
        )}

        <Text style={S.footer}>
          Generated by HiddenAtlas · hiddenatlas.travel
        </Text>
      </Page>
    </Document>
  );
}
