// WorkspacePDF — personalised trip guide using HiddenAtlas design language
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const TEAL = '#1B6B65';
const GOLD = '#C9A96E';
const CHAR = '#1C1A16';
const MUTED = '#6B6156';
const LIGHT = '#F4F1EC';

const S = StyleSheet.create({
  page: {
    paddingTop: 52, paddingBottom: 72, paddingHorizontal: 52,
    fontFamily: 'Helvetica', backgroundColor: '#FFFFFF', color: CHAR,
  },
  coverPage: {
    padding: 0, backgroundColor: '#0D3834',
  },
  coverInner: {
    padding: 56, flex: 1,
  },
  badge: {
    fontSize: 7, fontFamily: 'Helvetica-Bold', letterSpacing: 2.5,
    textTransform: 'uppercase', color: GOLD, marginBottom: 12,
  },
  h1: {
    fontSize: 32, fontFamily: 'Helvetica-Bold', color: '#FFFFFF',
    lineHeight: 1.2, marginBottom: 12,
  },
  coverSubtitle: {
    fontSize: 14, color: 'rgba(255,255,255,0.7)', lineHeight: 1.6, marginBottom: 32,
  },
  metaPill: {
    fontSize: 9, color: 'rgba(255,255,255,0.65)', marginBottom: 6,
  },
  coverFooter: {
    marginTop: 'auto', borderTopWidth: 0.75, borderTopColor: 'rgba(255,255,255,0.15)',
    paddingTop: 12,
    fontSize: 8, color: 'rgba(255,255,255,0.4)',
  },
  label: {
    fontSize: 7.5, fontFamily: 'Helvetica-Bold', letterSpacing: 2,
    textTransform: 'uppercase', color: TEAL, marginBottom: 8,
  },
  h2: {
    fontSize: 18, fontFamily: 'Helvetica-Bold', color: CHAR,
    marginBottom: 10, lineHeight: 1.25,
  },
  h3: {
    fontSize: 13, fontFamily: 'Helvetica-Bold', color: CHAR,
    marginBottom: 6, marginTop: 16,
  },
  body: {
    fontSize: 10, color: MUTED, lineHeight: 1.7,
  },
  divider: {
    borderBottomWidth: 0.75, borderBottomColor: '#E8E3DA', marginVertical: 18,
  },
  sectionTitle: {
    fontSize: 14, fontFamily: 'Helvetica-Bold', color: CHAR,
    marginBottom: 10, marginTop: 20,
  },
  bullet: {
    fontSize: 10, color: MUTED, marginBottom: 4, lineHeight: 1.5,
    paddingLeft: 12,
  },
  infoRow: {
    display: 'flex', flexDirection: 'row', marginBottom: 10,
  },
  infoLabel: {
    fontSize: 8, fontFamily: 'Helvetica-Bold', letterSpacing: 1,
    textTransform: 'uppercase', color: TEAL, width: 120, flexShrink: 0,
  },
  infoValue: {
    fontSize: 10, color: CHAR, flex: 1,
  },
  detailBox: {
    backgroundColor: LIGHT, padding: 16, borderRadius: 4, marginBottom: 16,
  },
  dayLabel: {
    fontSize: 7.5, fontFamily: 'Helvetica-Bold', letterSpacing: 1.5,
    textTransform: 'uppercase', color: TEAL, marginBottom: 3,
  },
  dayTitle: {
    fontSize: 13, fontFamily: 'Helvetica-Bold', color: CHAR, marginBottom: 5,
  },
  dayDesc: {
    fontSize: 10, color: MUTED, lineHeight: 1.65, marginBottom: 8,
  },
  itemRow: {
    display: 'flex', flexDirection: 'row', alignItems: 'flex-start',
    marginBottom: 6, paddingLeft: 8,
    borderLeftWidth: 2, borderLeftColor: TEAL,
  },
  itemTitle: {
    fontSize: 10, fontFamily: 'Helvetica-Bold', color: CHAR,
  },
  itemMeta: {
    fontSize: 9, color: MUTED,
  },
  bookingBadge: {
    fontSize: 7, fontFamily: 'Helvetica-Bold', letterSpacing: 1,
    textTransform: 'uppercase', color: GOLD, marginBottom: 2,
  },
  noteBox: {
    backgroundColor: '#FFFBF2', padding: 10, marginBottom: 8,
    borderLeftWidth: 2, borderLeftColor: GOLD,
  },
  noteTitle: {
    fontSize: 8, fontFamily: 'Helvetica-Bold', letterSpacing: 1,
    textTransform: 'uppercase', color: GOLD, marginBottom: 3,
  },
  noteContent: {
    fontSize: 10, color: CHAR, lineHeight: 1.6,
  },
  footer: {
    position: 'absolute', bottom: 28, left: 52, right: 52,
    fontSize: 8, color: '#B5AA99', textAlign: 'center',
    borderTopWidth: 0.75, borderTopColor: '#E8E3DA', paddingTop: 8,
  },
  bookingRow: {
    marginBottom: 10, paddingBottom: 10,
    borderBottomWidth: 0.5, borderBottomColor: '#E8E3DA',
  },
  bookingTitle: {
    fontSize: 11, fontFamily: 'Helvetica-Bold', color: CHAR, marginBottom: 2,
  },
  bookingMeta: {
    fontSize: 9, color: MUTED,
  },
  bookingRef: {
    fontSize: 9, fontFamily: 'Helvetica-Bold', color: TEAL,
  },
});

function formatDate(iso) {
  if (!iso) return '';
  try { return new Date(iso).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }); } catch { return iso; }
}

function formatDuration(min) {
  if (!min) return '';
  const h = Math.floor(min / 60), m = min % 60;
  return h > 0 ? (m > 0 ? `${h}h ${m}m` : `${h}h`) : `${m}m`;
}

function normalizeDay(d) {
  return {
    dayNumber:   d.dayNumber   || d.day     || 0,
    title:       d.title       || '',
    description: d.desc        || d.description || '',
    bullets:     d.bullets     || d.highlights  || [],
    tip:         d.tip         || d.insiderTip  || '',
  };
}

function Footer({ label }) {
  return <Text style={S.footer}>{label || 'Generated by HiddenAtlas · hiddenatlas.travel'}</Text>;
}

export function WorkspacePDF({ trip, itinerary, tripDays, tripItems, tripNotes, tripBookings, content, itineraryDayStops = [] }) {
  const safeContent = content || {};
  const itinDays  = (safeContent?.days || []).map(normalizeDay);
  const highlights = safeContent?.summary?.highlights || Array.isArray(trip.highlights) ? (trip.highlights || []) : [];
  const sorted = [...(tripDays || [])].sort((a, b) => (a.sortOrder || a.dayNumber) - (b.sortOrder || b.dayNumber));
  const tripTitle = itinerary?.title || trip.title || trip.destination || 'My Journey';
  const destination = itinerary?.destination || trip.country || trip.destination || '';

  return (
    <Document title={`${tripTitle} — My Trip`} author="HiddenAtlas">

      {/* ── Cover page ──────────────────────────────────────────── */}
      <Page size="A4" style={S.coverPage}>
        <View style={S.coverInner}>
          <Text style={S.badge}>HiddenAtlas · Personal Guide</Text>
          <Text style={S.h1}>{tripTitle}</Text>
          {itinerary?.subtitle && <Text style={S.coverSubtitle}>{itinerary.subtitle}</Text>}

          {destination && <Text style={S.metaPill}>{destination}</Text>}
          {trip.duration && <Text style={S.metaPill}>{trip.duration}</Text>}
          {trip.startDate && (
            <Text style={S.metaPill}>
              {formatDate(trip.startDate)}{trip.endDate ? ` — ${formatDate(trip.endDate)}` : ''}
            </Text>
          )}
          {trip.travellers && <Text style={S.metaPill}>{trip.travellers} traveller{trip.travellers > 1 ? 's' : ''}</Text>}

          <Text style={S.coverFooter}>hiddenatlas.travel</Text>
        </View>
      </Page>

      {/* ── Trip details page ────────────────────────────────────── */}
      {(trip.startDate || trip.travellers || trip.accommodationSummary || trip.arrivalInfo || trip.departureInfo || trip.generalNotes || (Array.isArray(highlights) && highlights.length > 0)) && (
        <Page size="A4" style={S.page}>
          <Text style={S.label}>Your journey</Text>
          <Text style={S.h2}>{tripTitle}</Text>

          {itinerary?.description && (
            <Text style={[S.body, { marginBottom: 16 }]}>{itinerary.description}</Text>
          )}

          <View style={S.divider} />

          {/* Personal details */}
          <View style={S.detailBox}>
            <Text style={[S.label, { marginBottom: 12 }]}>Trip details</Text>
            {trip.startDate && (
              <View style={S.infoRow}>
                <Text style={S.infoLabel}>Dates</Text>
                <Text style={S.infoValue}>{formatDate(trip.startDate)}{trip.endDate ? ` — ${formatDate(trip.endDate)}` : ''}</Text>
              </View>
            )}
            {trip.travellers && (
              <View style={S.infoRow}>
                <Text style={S.infoLabel}>Travellers</Text>
                <Text style={S.infoValue}>{trip.travellers}</Text>
              </View>
            )}
            {trip.accommodationSummary && (
              <View style={S.infoRow}>
                <Text style={S.infoLabel}>Accommodation</Text>
                <Text style={S.infoValue}>{trip.accommodationSummary}</Text>
              </View>
            )}
            {trip.arrivalInfo && (
              <View style={S.infoRow}>
                <Text style={S.infoLabel}>Arrival</Text>
                <Text style={S.infoValue}>{trip.arrivalInfo}</Text>
              </View>
            )}
            {trip.departureInfo && (
              <View style={S.infoRow}>
                <Text style={S.infoLabel}>Departure</Text>
                <Text style={S.infoValue}>{trip.departureInfo}</Text>
              </View>
            )}
            {trip.generalNotes && (
              <View style={S.infoRow}>
                <Text style={S.infoLabel}>Notes</Text>
                <Text style={S.infoValue}>{trip.generalNotes}</Text>
              </View>
            )}
          </View>

          {/* Highlights */}
          {Array.isArray(highlights) && highlights.length > 0 && (
            <View>
              <Text style={S.sectionTitle}>Trip Highlights</Text>
              {highlights.map((h, i) => (
                <Text key={i} style={S.bullet}>• {typeof h === 'string' ? h : String(h)}</Text>
              ))}
            </View>
          )}

          <Footer label={`${tripTitle} · HiddenAtlas`} />
        </Page>
      )}

      {/* ── Day pages ───────────────────────────────────────────── */}
      {sorted.map(tripDay => {
        const itinDay = itinDays.find(d => d.dayNumber === tripDay.dayNumber) || null;
        const dayTitle = tripDay.titleOverride || itinDay?.title || tripDay.title || `Day ${tripDay.dayNumber}`;
        const dayDesc  = tripDay.descriptionOverride || itinDay?.description || tripDay.description || '';
        // Prefer structured day stops; fall back to bullets
        const dayStops = itineraryDayStops.filter(s => s.dayNumber === tripDay.dayNumber)
          .sort((a, b) => (a.sortOrder ?? 0) - (b.sortOrder ?? 0));
        const bullets  = dayStops.length > 0 ? [] : (itinDay?.bullets || []);
        const tip      = itinDay?.tip || '';
        const dayItems    = (tripItems || []).filter(i => i.tripDayId === tripDay.id);
        const dayBookings = (tripBookings || []).filter(b => b.tripDayId === tripDay.id);
        const dayNotes    = (tripNotes || []).filter(n => n.tripDayId === tripDay.id);

        return (
          <Page key={tripDay.id} size="A4" style={S.page}>
            <Text style={S.dayLabel}>Day {tripDay.dayNumber}</Text>
            <Text style={S.dayTitle}>{dayTitle}</Text>
            {dayDesc ? <Text style={S.dayDesc}>{dayDesc}</Text> : null}

            {/* Structured day stops — preferred over legacy bullets */}
            {dayStops.length > 0 && (
              <View style={{ marginBottom: 10 }}>
                <Text style={[S.label, { marginBottom: 6 }]}>Places today</Text>
                {dayStops.map((stop, i) => (
                  <View key={i} style={{ flexDirection: 'row', marginBottom: 5, paddingLeft: 8, gap: 6 }}>
                    <Text style={{ fontSize: 9, color: MUTED, width: 10, flexShrink: 0, marginTop: 1 }}>·</Text>
                    <View style={{ flex: 1 }}>
                      <Text style={{ fontSize: 10, fontFamily: 'Helvetica-Bold', color: CHAR }}>
                        {stop.title}{stop.description ? ` — ${stop.description}` : ''}
                      </Text>
                      {stop.suggestedTime ? (
                        <Text style={{ fontSize: 8.5, color: MUTED }}>{stop.suggestedTime}</Text>
                      ) : null}
                    </View>
                  </View>
                ))}
              </View>
            )}

            {bullets.length > 0 && (
              <View style={{ marginBottom: 8 }}>
                {bullets.map((b, i) => (
                  <Text key={i} style={S.bullet}>· {typeof b === 'string' ? b : String(b)}</Text>
                ))}
              </View>
            )}

            {tip && (
              <View style={[S.noteBox, { borderLeftColor: GOLD, marginBottom: 12 }]}>
                <Text style={S.noteTitle}>Insider tip</Text>
                <Text style={S.noteContent}>{tip}</Text>
              </View>
            )}

            {/* User items */}
            {dayItems.length > 0 && (
              <View>
                <Text style={S.h3}>Your places</Text>
                {dayItems.map(item => {
                  const timePart = item.startTime && item.endTime ? `${item.startTime} → ${item.endTime}` : item.time || '';
                  const durPart  = item.durationMinutes ? formatDuration(item.durationMinutes) : '';
                  return (
                    <View key={item.id} style={[S.itemRow, { marginBottom: 8 }]}>
                      <View>
                        <Text style={S.itemTitle}>{item.title}</Text>
                        {(timePart || durPart || item.locationName) && (
                          <Text style={S.itemMeta}>{[timePart, durPart, item.locationName].filter(Boolean).join(' · ')}</Text>
                        )}
                        {item.notes && <Text style={[S.itemMeta, { marginTop: 2 }]}>{item.notes}</Text>}
                      </View>
                    </View>
                  );
                })}
              </View>
            )}

            {/* Day bookings */}
            {dayBookings.length > 0 && (
              <View>
                <Text style={S.h3}>Bookings</Text>
                {dayBookings.map(b => {
                  const meta = b.metadata || {};
                  return (
                    <View key={b.id} style={S.bookingRow}>
                      <Text style={S.bookingBadge}>{b.type}</Text>
                      <Text style={S.bookingTitle}>{b.title}</Text>
                      {b.locationName && <Text style={S.bookingMeta}>{b.locationName}</Text>}
                      {b.time && <Text style={S.bookingMeta}>{b.time}</Text>}
                      {meta.checkInDate && <Text style={S.bookingMeta}>Check-in: {meta.checkInDate}{meta.checkInTime ? ` at ${meta.checkInTime}` : ''}</Text>}
                      {meta.checkOutDate && <Text style={S.bookingMeta}>Check-out: {meta.checkOutDate}</Text>}
                      {b.confirmationReference && <Text style={S.bookingRef}>Ref: {b.confirmationReference}</Text>}
                      {b.notes && <Text style={S.bookingMeta}>{b.notes}</Text>}
                    </View>
                  );
                })}
              </View>
            )}

            {/* Day notes */}
            {dayNotes.length > 0 && (
              <View>
                <Text style={S.h3}>Notes</Text>
                {dayNotes.map(n => (
                  <View key={n.id} style={S.noteBox}>
                    {n.title && <Text style={S.noteTitle}>{n.title}</Text>}
                    <Text style={S.noteContent}>{n.content}</Text>
                  </View>
                ))}
              </View>
            )}

            <Footer label={`Day ${tripDay.dayNumber} — ${tripTitle}`} />
          </Page>
        );
      })}

      {/* ── General notes page ──────────────────────────────────── */}
      {(tripNotes || []).filter(n => !n.tripDayId).length > 0 && (
        <Page size="A4" style={S.page}>
          <Text style={S.label}>Notes</Text>
          <Text style={S.h2}>General notes</Text>
          <View style={S.divider} />
          {(tripNotes || []).filter(n => !n.tripDayId).map(n => (
            <View key={n.id} style={S.noteBox}>
              {n.title && <Text style={S.noteTitle}>{n.title}</Text>}
              <Text style={S.noteContent}>{n.content}</Text>
            </View>
          ))}
          <Footer label={`${tripTitle} · HiddenAtlas`} />
        </Page>
      )}

      {/* ── All bookings summary ─────────────────────────────────── */}
      {(tripBookings || []).filter(b => !b.tripDayId).length > 0 && (
        <Page size="A4" style={S.page}>
          <Text style={S.label}>Bookings</Text>
          <Text style={S.h2}>All reservations</Text>
          <View style={S.divider} />
          {(tripBookings || []).filter(b => !b.tripDayId).map(b => {
            const meta = b.metadata || {};
            return (
              <View key={b.id} style={S.bookingRow}>
                <Text style={S.bookingBadge}>{b.type}</Text>
                <Text style={S.bookingTitle}>{b.title}</Text>
                {b.date && <Text style={S.bookingMeta}>{formatDate(b.date)}{b.time ? ` at ${b.time}` : ''}</Text>}
                {meta.checkInDate && <Text style={S.bookingMeta}>Check-in: {meta.checkInDate}</Text>}
                {meta.checkOutDate && <Text style={S.bookingMeta}>Check-out: {meta.checkOutDate}</Text>}
                {b.locationName && <Text style={S.bookingMeta}>{b.locationName}</Text>}
                {b.provider && <Text style={S.bookingMeta}>{b.provider}</Text>}
                {b.confirmationReference && <Text style={S.bookingRef}>Ref: {b.confirmationReference}</Text>}
                {b.notes && <Text style={S.bookingMeta}>{b.notes}</Text>}
              </View>
            );
          })}
          <Footer label={`${tripTitle} · HiddenAtlas`} />
        </Page>
      )}

    </Document>
  );
}
